version: '2'
services:
    rimannoce-app:
        image: rimannoce
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rimannoce-mysql:3306/rimannoce?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rimannoce-mysql:
        extends:
            file: mysql.yml
            service: rimannoce-mysql
